### ISSUE TITLE
How are you using this with lamba?

### ISSUE THREAD

**Issue by jalevin** [shelfio/apache-tika-lambda-layer#2]
On my local machine I've been running this by forking the process, however, I'm using ruby + java to do that. 

Are you bringing a second runtime in? 
How would you run the tika server in the background so you can get the output with say curl?

Thanks

**Comment by vladholubiev** [comment]
Hey @jalevin 

Yes, we brought another layer with Java. We followed the steps from https://github.com/lambci/yumda to create a layer with Java package installed from the Amazon Linux 2 environment.

After unpacking Java layer it becomes available at `/opt/lib/jvm/java-1.8.0-openjdk-1.8.0.222.b10-0.lambda2.0.1.x86_64/jre/bin/java`. That's the path to java binary which we use to execute `tika-server.jar` to spawn a server in the background. 

It runs on `localhost:9998/tika` and we shoot POST requests w/ file content in the request body and get the extracted text back

**Comment by jalevin** [comment]
Awesome! Thanks for the tip. I'm running into one small issue which is that my java layer is coming in at 50.6mb, so I can't upload as a layer. Did you have to do any finessing to get this to work?

edit -- so I got this to work by using java-1.8 on Amazon linux 1 environment and java was only 17mb ??

Can I ask how you were able to get the process to run in the background and also make the curl request in the same function?

I've tried ```nohup /path/to/java -jar /opt/tika &``` and then curl, but it can't connect, I presume because the jar is not still running..

Thanks

**Comment by KnupMan** [comment]
Hey @jalevin 
Regarding your previous question - we published another lambda layer with Java 8 to make Tike running.
Here is the command to get Java 8, which you can package to the layer:
```bash
docker run --rm -v "$PWD"/java-layer:/lambda/opt lambci/yumda:2 yum install -y java-1.8.0-openjdk-headless.x86_64
```

It's more than 50MB (~53MB), so you need to save it on S3 and publish it using s3 path to zipped layer.

We have published the layer at `us-east-1`: `arn:aws:lambda:us-east-1:764866452798:layer:java:1`. 
Executable Java path using the layer will be `/opt/lib/jvm/java-1.8.0-openjdk-1.8.0.222.b10-0.lambda2.0.1.x86_64/jre/bin/java`.

Regarding your last question - we can start the Tika and make a request in the same function, by using https://github.com/shelfio/tika-text-extract package,

**Comment by KnupMan** [comment]
@jalevin just FYI - we just published a repo with the [Java 8 Lambda layer](https://github.com/shelfio/java-lambda-layer), so that would be easier for everyone to use it with Apache Tika.
Also, there is a [section in README](https://github.com/shelfio/apache-tika-lambda-layer#how-can-i-use-it-with-the-lambda-runtime-which-doesnt-have-java-installed), which actually now answers your question about the second runtime inside of the Lambda.

**Comment by greendesertsnow** [comment]
Can you guys please write down a step by step guide from installation to a simple usage scenario. I'm lost with the version 2 because they ruined the rest api for me, by removing the enableFileUrl...
