### ISSUE TITLE
Another error

### ISSUE THREAD

**Issue by ghost** [shelfio/apache-tika-lambda-layer#7]
Hey,
Tried adding arn:aws:lambda:us-east-1:764866452798:layer:apache-tika:1 under the Layers tab and got this:

Function not found: arn:aws:lambda:us-east-1:024334519364:function:tika-lambda (Service: AWSLambda; Status Code: 404; Error Code: ResourceNotFoundException; Request ID: 9a58c0c1-e347-4411-8a14-26bc17df061e; Proxy: null)

Can you please make the documentation even more simple? It's a little hard to understand.

**Comment by vladholubiev** [comment]
Hey @pazarbasifatih.

The `Function not found` error has nothing to do with the layer. Could you please search for a problem on your side?

**Comment by ghost** [comment]
I wish I could. Maybe my current knowledge doesn't let me do so, but I can't follow the Read.me file either. Am I missing something?
Java 8 Lambda Layer is not there,
Latest Apache Tika jar files are way larger than 50 MB.

Will this repository enable me OCR all languages?

**Comment by vladholubiev** [comment]
No OCR, for OCR check out https://github.com/shelfio/aws-lambda-tesseract

For Java 8 layer go here: https://github.com/shelfio/java-lambda-layer

Attach 2 layers, first Java 8 layer, then Apache Tika layer

**Comment by ghost** [comment]
I'm getting 404 for  https://github.com/shelfio/java-lambda-layer
And Tika is superior to Tesseract as tesseract can only process image files while Tika can go through all office files and PDFs.

**Comment by vladholubiev** [comment]
@pazarbasifatih sorry, I didn't know that repo is private 😅  I've just made it public

**Comment by vladholubiev** [comment]
As for Tika, unfortunately, this layer doesn't have Tesseract inside to Make Tika do OCR inside PDFs

**Comment by ghost** [comment]
I was hopeful... But it's ok. Tika is a large file.
I believe the best serverless OCR solution is to dockerize Tika in Fargate and trigger a Lambda function when user uploads files to S3 bucket and write the extracted pages back to S3.
Have a nice day.
